### ISSUE TITLE
pom not committed back to master unless --use-conveyal-workflow is used

### ISSUE THREAD

**Issue by erzz** [conveyal/maven-semantic-release#50]
We just want a really simple usage which could be summarised as:

* DO create the semantic-release
* DO update pom.xml with new version
* DO commit & push back to master with new tag and new pom
* NO merge back to any other branch (i.e. no usage of `--dev-branch=dev`)
* NO publishing to Maven repo as we have a job that will run after this and deploy to our private artifactory

So sure, I use the `--skip-maven-deploy` flag to satisfy the last point. But if I then use this command:

`semantic-release --skip-maven-deploy --disable-snapshot-skip-ci --disable-final-skip-ci --additionalFilesToCommit pom.xml,CHANGELOG.md`

I do not get a new pom.xml committed back to master, only the CHANGELOG.md.

The only way I can get the pom in the commit back to master is to add the `--use-conveyal-workflow` which I don't "want" which of course makes the job fail due to no --dev-branch being added.

Is there a flag I am missing or can use for the simple version of the job I want to use :)

Here is the releaserc for reference and the entire Gitlab CI job.

**.releaserc.json**
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@conveyal/maven-semantic-release",
    "@semantic-release/gitlab",
    [
      "@semantic-release/git",
      {
        "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
      }
    ]
  ],
  "branches": ["master"]
}
```

**ci job**
```
semantic-release:
  image: openjdk:11-jdk
  stage: release
  tags:
    - "dev"
  variables:
    GITLAB_TOKEN: <REDACTED>
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates nodejs
    - npm install -g semantic-release @semantic-release/gitlab @conveyal/maven-semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git
    - echo "$MAVEN_SETTINGS_FILE" > maven-settings.xml
  script:
    - touch CHANGELOG.md
    - semantic-release --use-conveyal-workflow --skip-maven-deploy --disable-snapshot-skip-ci --disable-final-skip-ci --additionalFilesToCommit pom.xml,CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md
      - pom.xml
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
```
